jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Debug
        run: echo ${{ env.BRANCH }}